import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/ui/Header";
// import { Provider } from "react-redux";
import store from '../store/store'
import ReduxProvider from "@/components/ReduxProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Space Bird ToDos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
